### ISSUE TITLE
Sensor.measure(???)

### ISSUE THREAD

**Issue by TTitscher** [BAMresearch/fenics-constitutive#22]
For linear elasticity, the displacements u and the residual R seem to be sufficient for postprocessing. Thus, we currently have `sensors.measure(u, R)`. For nonlinear problems, we may also want to measure (aka post-process) internal variables. And for multiphysics problems, we measure other fields. 

One idea was to pass the whole problem as an argument. What could be the disadvantages? If there are none, "just" implement it :)

**Comment by eriktamsen** [comment]
So far I have not found a better solution for this either, how ever I have some additional thoughts on the whole sensor concept, therefore I opened issue #24.
But my answer to the question, what to pass the sensor, I would agree the pass the whole problem.
Still, there are points to be discussed: The required fields will need to be standardized, eg. 'problem.u', 'problem.T' etc... then, if the field is not continuous, quadrature point values, would be required. The sensor then restricted to a specific field? Again the location of the function field on which to project to quadrature points, will need to have a standardized name like 'problem.visu_space'
I think this overlaps with issue #21
