### ISSUE TITLE
A simple solver for small strain problems

### ISSUE THREAD

**Issue by srosenbu** [BAMresearch/fenics-constitutive#37]
Although, we don't want to make this a comprehensive library, at least for the standard incremental small strain models, we should have a solver/or problem definition similar to `dolfinx.fem.petsc.NonlinearProblem`

**Comment by srosenbu** [comment]
Sounds good;)
Do you plan on doing the model with `numba` or is it possible to use numpy functions for everything?

**Comment by pdiercks** [comment]
It would be simplest to use the [old implementation using numba](https://bamresearch.github.io/fenics-constitutive/examples/ramberg_osgood.html#solution-of-the-constitutive-law) or implement the same function with cpp or rust if we dont want to use `numba`.

**Comment by srosenbu** [comment]
I don't see a problem with using `numba`
