### ISSUE TITLE
Zenodo doi

### ISSUE THREAD

**Issue by srosenbu** [BAMresearch/fenics-constitutive#55]
For the paper, we should create a Zenodo doi. For that purpose, we should also start with a citation file [(example)](https://github.com/BAMresearch/FenicsXConcrete/blob/main/CITATION.cff) 

I think almost all authors are listed already in the linked citation file. @saifr68 do you already have an ORCID?
Do we include Thomas as author in the new version?

**Comment by joergfunger** [comment]
@TTitscher vielleicht kann Thomas kurz schreiben, ob er als Co-Author auf dem Paper erscheinen möchte, und wenn ja, mit welcher Email-Adressse.

**Comment by TTitscher** [comment]
Hi guys, nice to see that fenics-constitutive is being continued in fenicsx! 
I think with 7b69162, you essentially created a new project with own ideas while reusing the name of the repository. And I like it! So it's perfectly fine for me, if you leave me out as coauthor! (both paper and code)
Good luck!

**Comment by srosenbu** [comment]
Thank you:)
Just to clarify: The paper that we are talking about is built upon the one you started with Vitaliy, but it goes into a more general direction of how to build constitutive models with fenicsx and the UMAT bindings is an example for that. We basically don't use any of the old code, but we were definitely inspired by what the two of you did. So you will probably get at least an acknowledgment in the paper;)
