### ISSUE TITLE
Using 3D models for uniaxial strain and palne strain

### ISSUE THREAD

**Issue by srosenbu** [BAMresearch/fenics-constitutive#57]
If we have a uniaxial strain experiment, we can expand the strain 1D strain $\varepsilon_{11}$ to the 3D strain $[\varepsilon_{11}, 0, 0, 0, 0, 0]$. Similarly with plane strain. This way, it is straightforward to use a 3D model for uniaxial strain or plane strain without reimplementation.

Do we want functionality to use 3D models for uniaxial strain and plane strain? Or is this behaviour that we want to discourage because it is unnecessarily expensive to evaluate the 0-components?

I could use this for the paper because we have written the models for 3D (and I don't know if the UMATS are written to deal with plane strain)

**Comment by joergfunger** [comment]
I would say it is maybe not the optimal implementation, but it is correct. And I doubt that even our 3D models are "optimal", so I see no reason to exclude that option.

**Comment by srosenbu** [comment]
Alright. Then I will prepare a PR
