### ISSUE TITLE
PyPI upload

### ISSUE THREAD

**Issue by TTitscher** [BAMresearch/fenics-constitutive#8]
The issue with our python package #7 is that it is compiled and thus platform dependent. PyPI does not allow such a package, details [here](https://www.python.org/dev/peps/pep-0513/#rationale).

The idea is to convert the specific binaries to a "manywheels" thing using e.g. https://pypi.org/project/auditwheel/ 
This current fails because: 
>auditwheel: error: cannot repair "dist/constitutive-0.1-cp38-cp38-linux_x86_64.whl" to "manylinux1_x86_64" ABI because of the presence of too-recent versioned symbols. You'll need to compile the wheel on an older toolchain.

... and after my fight agains github actions, I am currently not in the mood deal with that and just want to write the progress somewhere.

**Comment by pdiercks** [comment]
In that case I would suggest that I try to figure out the conda recipe manually (that is without using grayskull) and that do not upload it to PyPI.
